apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: APP_NAME
spec:
  selector:
    matchLabels:
      app: APP_NAME
  endpoints:
    - port: http
      interval: 10s
      path: /actuator/prometheus